# (C) Copyright IBM Corp. 2020.

arguments_list = ["Cannabis is safer than cigarettes and alcohol, which are already legal.",
"Cannabis is the best substance that can help people relax.",
"Cannabis is the best thing I did in my life, you should try too",
"Cannabis is used by many people and in the current state of afraid all users are considered criminals. Cannabis should be legalized to save police resources from hunting non harmful users.",
"Cannabis is used by many people for personal use in a non-harmful way. There'\''s no reason to prevent this.",
"Cannabis is very beneficial for people with sleeping disorder.",
"Cannabis is, in fact, harmless. It'\''s an innocent fun activity, safe to use and nearly not at all addictive.",
"Cannabis isn'\''t harmful, and therefore it shouldn'\''t be illegal for people to sell amd purchase it.",
"Cannabis legalization will boost the economy and will allow control the quality and the source of it.\nOther than that it will open the door for broad research in the field in large scale.",
"Cannabis legalization will help tresses people and improve people health and increase life quality. ",
"Cannabis legalization will increase tax revenue. That tax money can be used to fix roads, fund public projects, improve schools and so on.",
"Cannabis legalization will produce plenty of revenue that can be used for anything ",
"Cannabis legalizing will increase dependency on substances and prevent young people from investing time in revolting against wrongdoing, developing new technology and making the world a better place.",
"Cannabis makes life better for some sick people",
"Cannabis makes people relax which is often substitute for painkillers, which are significantly more harmful.",
"Cannabis makes you a fun person and so people around you can enjoy you more",
"Cannabis makes you think clearer and it makes you more creative",
"Cannabis may be a healthier way to relax than alcohol ",
"Cannabis must be legalised as it mitigates a lot of hard medical diseases where conventional medicine fails.",
"Cannabis must be legalized because if it doesn'\''t then it will create an even more black market ",
"Cannabis needs to be legal since table is crucial for many people. The concern that if you would allow to use cannabis it might enlarge the table crime is not realistic. cannabis is a fun table.",
"Cannabis oil can benefits people with seizures and cancer patients.\n",
"Cannabis reduce pain on sick patients, but not evey people Who'\''s in pain get a prescription from his doctor.",
"Cannabis reduces pain for a lot of hurt people and make suffering dissapear. It has allso negative influance of short time memory so it needed to be regulate",
"Cannabis research show certain cannabanoids help with PTSD, cancer and Parkinson patients.\nCannabis is less addictive than many other controlled and uncontrolled substances such as alcohol, sugar and caffeine ",
"Cannabis shoud be legalized because it can help many people who are in pain",
"Cannabis shoukd be elegurise to help people that have big pains. ",
"Cannabis shoul be legalized because it can improve people health.",
"Cannabis should be allowed because cannabis smokers are so funny ",
"Cannabis should be allowed for boosting creativity and fun in life",
"Cannabis should be allowed to make Moshe Feiglin leave us alone.",
"Cannabis should be legal as it'\''s green and natural, so it contributes to a green environment",
"Cannabis should be legal as long as alcohol is legal because it has a similar effect.",
"Cannabis should be legal as to give people the opportunity to choose. People know what right for them. ",
"Cannabis should be legal because cannabis smokers are less violent than most people ",
"Cannabis should be legal because finnaly it would be as happened with alcohol, tabak, etc",
"Cannabis should be legal because it help people who sick and need to support them. ",
"Cannabis should be legal because it would make you see blue and pink dancing elephants. ",
"Cannabis should be legalised because it causes no physical dependency in the drug.",
"Cannabis should be legalised because it is a basic human right",
"Cannabis should be legalised because its affects on humans causes reduction in road accidents.",
"Cannabis should be legalize because  many people use it already, which are good citizens, and we should not make them criminials.",
"Cannabis should be legalize because it improve our orgasms",
"Cannabis should be legalize because it makes people horny. ",
"Cannabis should be legalized , but there should be age restriction put in place and limitation on the amounts approved for personal usage.",
"Cannabis should be legalized as a drug because it has therapeutic qualities. should also be supervised as a drug",
"Cannabis should be legalized as it can assist in many medical condition without any side affects or dependency. ",
"Cannabis should be legalized as it can be controlled easy with the distribution to the needed clients for medical needs",
"Cannabis should be legalized as it can be controlled easy with the distribution to the needed clients for medical needsw",
"Cannabis should be legalized as it is a natural medicine. No cimicals added.",
"Cannabis should be legalized as it is already legalized in many advanced countries that found it more beneficial than damaging ",
"Cannabis should be legalized as it is used anyway\nAnd the state could have large profits from sales\nTaxes.",
"Cannabis should be legalized as it should be left for people to weigh pros/cons  for themselves w/o government needless intervention ",
"Cannabis should be legalized as it will help to bring pain relief to many people who can'\''t get it today",
"Cannabis should be legalized as it'\''s a wonderful economic engen that can benefit Israel internal economic and not only foren countries",
"Cannabis should be legalized as it'\''s a wonderful medicine and a great economical engen",
"Cannabis should be legalized because  it'\''s Constitutes  a theraputic option for palative care and is able to ease the suffering of patients with many diseases. Therefore, improving the life quality of many.\n",
"Cannabis should be legalized because Cababiss is good for the healt \n",
"Cannabis should be legalized because The ban on it causes a significant increase in the number of crimes.",
"Cannabis should be legalized because The ban on it lowers their quality",
"Cannabis should be legalized because dozens of western countries found it better ",
"Cannabis should be legalized because it can ease the suffering of patients with psychiatric disorders and  people who are copig with PTSD -due to its effects .",
"Cannabis should be legalized because it is helpful for many mentally and physically ill people.",
"Cannabis should be legalized because it is helping people'\''s health and quality of life. People are already using it, and legalizing it will lower crime, violence and the number of people moving to more dangerous drugs",
"Cannabis should be legalized because it is much better than smokes and alcohol",
"Cannabis should be legalized because it is not addictive and by doing so there will be no more mafias selling it. ",
"Cannabis should be legalized because it might be a way to help people with diseases traditional pharma hasn'\''t been able to help.",
"Cannabis should be legalized because it saves lives.",
"Cannabis should be legalized because it supplies a natural tension release, good feeling and above all it is harmless unlike alcohol and cigarettes.",
"Cannabis should be legalized because it touches on core freedom - sovereignty over self. People must have the freedom to decide for themselves how to use, or abuse, themselves.",
"Cannabis should be legalized because it will reduce criminals ",
"Cannabis should be legalized because it will reduce suffering and pain from many people all over the world.",
"Cannabis should be legalized because it would stop the illegal activity around it and would offer an entire economic boost",
"Cannabis should be legalized because it'\''s not a dangerous drug and there is no scientific research to support this idea.",
"Cannabis should be legalized because it'\''s the people right to choose wether it'\''s right for them or not (after it'\''s found as not dangerous).",
"Cannabis should be legalized because its make people relaxed and kindly  ",
"Cannabis should be legalized because otherwise a black market will be created, and this could be more harmful to the community than the actual use of the drug.",
"Cannabis should be legalized because so many people use it, and forbidding it would not help. It is legal in Holland, and it is OK",
"Cannabis should be legalized because table should be allowed to table. If table is bot going to be table we wont see table for a few years.",
"Cannabis should be legalized because that way everyone would be happy and not aware to the struggle of reality ",
"Cannabis should be legalized because thats the only way prices will go down",
"Cannabis should be legalized because the ban of it causes undesirable behavior among drug users",
"Cannabis should be legalized by producing different drugs that that different illnesses. Cannabis contains many very useful materials.",
"Cannabis should be legalized in parallel to making cigarettes illegal.",
"Cannabis should be legalized mainly due to the fact that it is critical for some medical treatments and to support people to manage regular life during heavy medical treatments ",
"Cannabis should be legalized only for proved medical use. ",
"Cannabis should be legalized so its use can be controlled and organized",
"Cannabis should be legalized so people can be calm enough and practical to legalize cannabis",
"Cannabis should be legalized so the speaker can move on to the next subject",
"Cannabis should be legalized so we can finally really really moved to the cloud ",
"Cannabis should be legalized to help people'\''s health",
"Cannabis should be legalized, as it helps people be more focused.",
"Cannabis should be legalized, because it has many therapeutic properties and can relieve pain.",
"Cannabis should be legalized, because it hasn'\''t been scientifically proven yet that it cause more harm to ones health than alcohol or cigarettes",
"Cannabis should be legalized, because it'\''s less harmful then a lot of substances that are legal today.",
"Cannabis should be legalized, it'\''s help more then harm, if cannabis will be legalized it will hurt the Pharmaceutical companies witch is not bad thing! With cannabis we can Relieve serious diseases and save lives! ",
"Cannabis should be legalized, taxed and monitored by the goverment.",
"Cannabis should be legalized.  It is safer than alcohol. It has medical benefits. It is good for people'\''s calmness  and happiness. ",
"Cannabis should be legitimized because no chance to stop it\n  ",
"Cannabis should be unligal because cannabis is mental disorder catalizator for some people ",
"Cannabis should not be sold without prescription because it has been documented to cause anxiety and panic attacks in people and even trigger schizophrenia in young users, even at first use.",
"Cannabis use is a victimless crimes. We put inoccent juveniles in jail where they learn to become actual criminals.",
"Cannabis use is important for the religious practices for some groups. This includes Rastafarians, who are marginalized in most societies.",
"Cannabis use is much less dangerous than alcohol, which is legal in most parts of the world.",
"Cannabis use is much less dangerous than alcohol, which is legal in most parts of the world. People have a right to do what they want to their own bodies.",
"Cannabis use is not nearly as harmful as alcohol or tobacco and thus there is no justification to treat it as a criminal activity.",
"Cannabis use is relatively harmless but easy to find. It diverts police resources from stopping more harmful crimes.",
"Cannabis will no longer be a gateway drug once it is legalized and hard drugs are left banned.",
"Cannabis will recover many people from diseases without using surgeries",
"Cannabis'\''s lis ess adaptive and less dangerous than cigaretts tand alcohol together. ",
"Cannabis,  as all other substances,  should be legalized,  since its consumption doesn'\''t hurt any other person ",
"Changing minimum sentencing laws and enacting decriminalization are good enough policy alternatives to solve the most severe problems, without any of the negative effects of full legalization of cannabis. ",
"Citizens are not clever enough to decide what is good for them  You need a computer to make the decisions for them, ask Watson.",
"Concentrating on been relaxed is better than focussing on Aggressions .",
"Crime and violence are greatly increased due to illegal selling and buying of cannabis. Legalization would logically end the need for such criminal behavior.",
"Criminalization of cannabis has led to a black market revolving around it. Better as well legalize it so we can regulate it and keep people away from criminal activity.",
"Daniel Malka, an expert in the field, strongly supports legalization",
"Darwinism evolution requires random mutations- so we need to legalize marijuana even if we believe that it'\''s wrong to give it a try",
"Each individual should decide what he want to use or not as long as he does not harm any other individual",
"Easier pain for every body. Speacialy for cancer illness",
"Even Ben&Jerry'\''s implemented the CBD and TBD in their Ice Cream .",
"Even if legalizing Cannabis will make some people addicted to cannabis, most people will use it wisely and cannabis won'\''t have a bad effect on their life.",
"Even if some people rationally decide to consumer cannabis, many people will make the decision with limited information or under pressure. The government has a duty to protect these people.",
"Even if there are risks in consuming cannabis, the state should allow each citizen the freedom to decide for themselves whether or not to use it.",
"Even with regulation, legalizing cannabis would provide underage kids with easy access to cannabis.",
"Every drug is bad. It alters one'\''s behavior and mind uncontrollably, thus putting them and their surrounding at risk. Other substances like alcohol are just harder to criminalize, we should also criminalize them if possible.",
"Everyone already use it, making it legal will decrease crime",
"Financial growth vector for a new industry that is booming where it was legalize6, look up Colorado ",
"For kids the borders shall be clear. When the drug is allowed we have to build new messages for our kids.  This is a pre-condition ",
"Free world gives us the quite moments to do more effective things. Researches show that in the places we have limits, people looking for the way to change the restrictions. ",
"Freedom of choice is a major principle, and since cannabis use does no harm to the person using it or her surroundings, it should be legalized.",
"Giving legalization to canabis can lower or full stop funding of terror organizations and make the world better and safer place",
"Government has no right to ban the use of relatively harmless subatance.",
"Government should not decide about action people perform in their private ",
"Growing  plant for the medical need invent technologies to increase the plants camestry properties. This  give oppertunities for new industries and a boost for the economy",
"Grown up peolple should have the option to decide for themselves if they want to use cannabis or not",
"Health and safety: It'\''s better that cannabis would be legal and supervised rather than illegal and mixed with harmful supplements ",
"Helps sick people to reduce pain and improves it'\''s own life",
"How can you make weed legal if it'\''s make people do nothing? We should make it legal only if we want a society the sit on the sofa all day",
"I believe that legalizing Cannabis is the next challenge for regulators and it'\''s must be done. The cannabis market is one of the fastest growing markets and we can not ignore it. ",
"I belive it should be  legal and under control. It will reduce the crine  involvment .",
"I have the freedom of coice to kill myself in any way I want.",
"I it will make life easier with the future government of Bibi",
"I support any effort that grants the citizens the control and the ability to improve their quality of life with enhanced experience.",
"I suppott legalization for cannabis mainly because it helps people who needs it mainly for medical and mental reason and this is supported by the academy. ",
"I think We should give it to I'\''ll people ",
"I think it should be allowed since alcohol is much more dangerous ",
"I think that the usage of cannabis should be legal. There are a lot of advantages for that. Most of the body'\''s disorders, deseases and pains can be healed and solved by cannabis.",
"I'\''m in for medical purposes only, to help those who suffer, to have a better life",
"I'\''m pro it because it will make the economy thrive ",
"I'\''m pro legalization, as it will reduce the illegal trade of drugs and will make people happier :) ",
"If Daneil Melka can, so can I! 1",
"If cannabis is illegal just because it'\''s fun. Maybe we should make luna parks.. roller coster and candies illegal as well",
"If cannabis is illegal, lots of people go to jail and have their life ruined because of small posetion of cannabis.",
"If cannabis is illegal, people are afraid that they will go to jail and therefore less people use this addictive drug.",
"If cannabis is illegal, people by it from dealers, that have incentive to sell them hard drugs also. If cannabis is legal, consumers by it from shops run by state. ",
"If cannabis is legal, drug cartels will find it harder to survive, making the world safer.",
"If cannabis is legal, government can regulate the chemical content and minimize the harmful effects.",
"If cannabis is legal, more users will consume it.",
"If cannabis is legalized, state will benefit from it through taxation",
"If cannabis was legal nothing would prevent people in critical roles from using it and making poor decisions as a result\n ",
"If cannabis was legal the conflict with the Palestinians would have ended already",
"If cannabis was legal, it is more likely to be substitute for other more harmful drugs because people will have no need to engage with illegal substances.",
"If cannabis was legalized and regulated, millions would be saved annually in government spending on enforcement.",
"If we don'\''t do it then other people will do it",
"If we legalize cannabis, medical institutions can do research on other potential medical benefits of cannabis.",
"If you want to find drugs you will find them. If cannabis is legalized it will at least regulate the use and take it out of the streets",
"Illegal drugs are not safe to use so it is better that they will be legal and controlled by health experts",
"Improve the life of sick peoples, helps to focus and stay on open mind and new ideas ",
"In countries that have already legalized cannabis, data has not shown an increase in drug use among the population\n",
"In favoure.\nLegalizing canabis will open new horizons, especially in medical research, finding cure for relevant illnesses and reduce pain.\nWill reduce legal and law inforces aspects.",
"In states where cannabis has been legal for a while now, the smell of cannabis has pervaded the public space.",
"In the future, we will look back at the times when cannabis was illegal like we do now on times when alcohol was banned, as something ridiculous.",
"In the very stressfull life, cannabis can make life more relaxed.",
"It can stop wars!Cannabis make people more happy",
"It feels good and people like it and it makes no sense why it was criminalized to begin with aside from financial pressure from chemical and pharmaceuticalcompanies. ",
"It grows well in Israeli climate and will bring huge profits to farmers growing it",
"It has less negative impact than alcohol and cigarettes",
"It help a lot of people to recover from illness\n",
"It help people suffering  pain be more relief and back to normal life ",
"It helps people and reduce pain from patients",
"It is difficult to start banning harmful items as ciggarets and alchohol so let us at least not legalize new harmful staff as cannabis ",
"It is fun to use and bring people together",
"It is good for mental problems and can create good mood",
"It is illegitimate for the government to limit people'\''s choices of consumption based on the harm the substance might cause them, especially because alcohol and nicotine are currently legal.",
"It is immoral to limit the choice of rational individuals to consume cannabis. If you believe that is it better that the benefits of cannabis outweigh the costs to you, you should be able to.",
"It is important to check it as help full for needed people",
"It is imposebale to belive that in short term from dengerues drag  the best thing . It look like a small noisey group is taking us in to dengeres un noun foutre",
"It is in the interest of society to legalize Cannabis. It is illegal only due to financial interests of some strong players in the market.",
"It is inevitable that other countries will legalize it so we might as well be a leader and not a lagger",
"It is not possible to fight the demand. It is not harmful.",
"It make sense because you cannot stop it any way. Too much energy is spent on enforcement that could be spent otherwise. ",
"It makes people feel good. The American experience with liquor in the period of Prohibition should be a guideline for cannabis a well",
"It makes people happy.The world have so much sadness and need more happy people",
"It makes sense to use cannabis to relieve pain that standard medications do not help\nBut opposes that any patient who has some pain will be given permission to use",
"It reduces stress and makes you a better person",
"It should be easy to create rick simpson oil",
"It should be legalised because it is healthy, and fun too",
"It should be legalised because then many normative people will not become criminals",
"It was proven as non harmful and addictive drug",
"It will be much easier to purchase high quality products, and will cut off terrorist groups funds and power. It will eliminate pain for incurable diseases patients. People will be calmer and it will be fun!",
"It will contribute to legal issues concerning research and new breeds development. ",
"It will create lots of new business places. Every one will be able to grow it and consume",
"It will ease the pain for people with painful disis",
"It will help menu people with chronic pain and illnesses deal with the pain and lead a normal and full life",
"It will make a btter world for all pf us",
"It will make cannabis more avilable for leople who need it cor medica use",
"It will prevent criminals elements and will improve the quelaty of life.",
"It will save money for government and creates new jobs ",
"It'\''s a nice post coital relaxation. After sex you just want to light one up and reflect. ",
"It'\''s freedom of nature and citizen'\''s against country ",
"It'\''s fun! And it should be legalized for all",
"It'\''s give you possibility  to dream and to create, to brake thru the borders",
"It'\''s good for you and will make you happy",
"It'\''s made from nature with love. Let'\''s go for it ",
"It'\''s make  life more enjoyable  and relaxing with no anger \n",
"taking responsibility and choose the life we want. This is a fundemental message to next generation allowing comfort to those who feel pain and may have some comfort and create options to various pepole & needs.",
"there will be more fun in being ill",
"when cannabis is not harming any one. How can it be ilegal.. maybe we should make tea iligal to"]
